development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: trianglebattle_voting_2011
  username: root
  password: d3pl0y
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: botb_voting_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: trianglebattle_voting_2011
  username: trianglebattle
  password: tr14ngl3b4ttl3
  socket: /var/run/mysqld/mysqld.sock
